package com.lalilu.lmusic

object Config {
    const val BASE_URL = "https://apis.lalilu.cn/"

    const val LAST_PLAYED_SP = "LAST_PLAYED_SP"
    const val LAST_PLAYED_ID = "LAST_PLAYED_ID"
    const val LAST_PLAYED_LIST = "LAST_PLAYED_LIST"
    const val LAST_PLAYED_POSITION = "LAST_PLAYED_POSITION"

    const val KEY_SETTINGS_MEDIA_UNKNOWN_FILTER = "KEY_SETTINGS_MEDIA_UNKNOWN_FILTER"
    const val KEY_SETTINGS_KANHIRA_ENABLE = "KEY_SETTINGS_KANHIRA_ENABLE"
    const val KEY_SETTINGS_LYRIC_GRAVITY = "KEY_SETTINGS_LYRIC_GRAVITY"
    const val KEY_SETTINGS_LYRIC_TEXT_SIZE = "KEY_SETTINGS_LYRIC_TEXT_SIZE"
    const val KEY_SETTINGS_SEEKBAR_HANDLER = "KEY_SETTINGS_SEEKBAR_HANDLER"
    const val KEY_SETTINGS_STATUS_LYRIC_ENABLE = "KEY_SETTINGS_STATUS_LYRIC_ENABLE"
    const val KEY_SETTINGS_IGNORE_AUDIO_FOCUS = "KEY_SETTINGS_IGNORE_AUDIO_FOCUS"
    const val KEY_SETTINGS_REPEAT_MODE = "KEY_SETTINGS_REPEAT_MODE"

    const val KEY_REMEMBER_IS_GUIDING_OVER = "KEY_REMEMBER_IS_GUIDING_OVER"

    const val DEFAULT_SETTINGS_MEDIA_UNKNOWN_FILTER = true
    const val DEFAULT_SETTINGS_KANHIRA_ENABLE = false
    const val DEFAULT_SETTINGS_LYRIC_GRAVITY = 1
    const val DEFAULT_SETTINGS_LYRIC_TEXT_SIZE = 16
    const val DEFAULT_SETTINGS_SEEKBAR_HANDLER = 0
    const val DEFAULT_SETTINGS_STATUS_LYRIC_ENABLE = false
    const val DEFAULT_SETTINGS_IGNORE_AUDIO_FOCUS = false
    const val DEFAULT_SETTINGS_REPEAT_MODE = 0
}